Vagrant.configure("2") do |config|
  config.vm.box = "almalinux/8" # Použití podporované distribuce
  config.vm.hostname = "bytcinebyt" # Unikátní název hosta
  config.vm.network "forwarded_port", guest: 80, host: 8080 # Port pro webové rozhraní
  config.vm.network "forwarded_port", guest: 22, host: 2222 # SSH přístup
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.cpus = 2
  end
  config.vm.provision "shell", path: "scripts/install_zabbix_server.sh" # Instalace serveru
  config.vm.provision "shell", path: "scripts/install_zabbix_agent.sh" # Instalace agenta
end
